server:
  port: 8081

spring:
  application:
    name: FridgeFeast

  datasource:
    url: jdbc:mysql://localhost:3306/ttcs
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huydn123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true